### PR TITLE
Fix payments not possible via digital wallets when customer address is in a country other than the stripe account 

### LINKED ISSUE #93: [SW5] Payment request fails because localization of user is used instead of localization of billing company
To create a [payment request](https://stripe.com/docs/js/payment_request/create), information about the localization of the company that receives the payment is mandatory, to ensure that it is located in a country that is supported by Stripe.

However, in the Checkout process, we gather the information from the paying user and pass it as payment request, instead of the localization of the billing company.
This leads to an error, in case the user is located in a country, of which payments can be accepted, but that are not supported as company residence countries.

Wrong information about the country code is gathered here:
https://github.com/pickware/ShopwareStripePayment/blob/cb00b39f5b3a43d5f2b0a89ea09cf6dc72abebe8/Views/frontend/checkout/confirm.tpl#L84

### PR DESCRIPTION
**Pull request by JanRogge**
**Summary**

Currently for StripePayments we use the country code of the customer which is wrong since it needs to be the country code which is set in the stripe account.
When updating the plugin we use the last 2 digits of the ISO Code from the default shops localization as a default stripe account country code. This will be updated to the country code of the stripe account if the stripe config gets saved with a valid secret key. 

Closes #93

### CODE REVIEW

File: Bootstrap.php [hunk 1]
```diff
@@ -10,10 +10,12 @@
 }
 
 use Shopware\Models\Config\Element;
+use Shopware\Models\Config\Form;
```
Comment (felixbrucker) [inline Bootstrap.php:13]:
```suggestion
```

File: Bootstrap.php [hunk 2]
```diff
@@ -336,6 +338,15 @@ public function update($oldVersion)
             case '5.3.3':
                 // Nothing to do
             case '5.3.4':
+                if (!Util::getConfigValue('stripeAccountCountryIso')) {
+                    $defaultShopLocale = $this->get('db')->fetchOne(
+                        'SELECT locale FROM s_core_locales l JOIN s_core_shops s ON s.locale_id = l.id WHERE s.default = 1'
```
Comment (felixbrucker) [inline Bootstrap.php:343]:
```suggestion
                        'SELECT locale.locale
                        FROM s_core_locales locale
                        JOIN s_core_shops shop ON shop.locale_id = locale.id
                        WHERE shop.default = 1'
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,16 @@
+## NEXT PATCH RELEASE
+
+### en
+
+* Fixes a bug that prevented payments with digital wallets (Apple Pay, Google Pay, ...) if the country of the customer and the country of the configured Stripe account differed.
```
Comment (felixbrucker) [inline CHANGELOG.md:5]:
```suggestion
* Fixes a bug that prevented payments with digital wallets (Apple Pay, Google Pay, ...) if the country of the customer and the country of the configured Stripe account differ.
```

File: Subscriber/Backend/ConfigSubscriber.php [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+     */
+    public static function getSubscribedEvents()
+    {
+        return [
+            'Shopware_Controllers_Backend_Config::saveFormAction::after' => 'onAfterSaveFormAction',
+        ];
+    }
+
+    /**
+     * Handle the retriving of the stripe account country and saving it to a hidden config value
```
Comment (felixbrucker) [inline Subscriber/Backend/ConfigSubscriber.php:29]:
```suggestion
     * Handle the retrieving of the stripe account country and saving it to a hidden config value
```

File: Subscriber/Backend/ConfigSubscriber.php [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+     *
+     * @param \Enlight_Hook_HookArgs $args
+     */
+    public function onAfterSaveFormAction(\Enlight_Hook_HookArgs $args)
+    {
+        $subject = $args->getSubject();
+        $data = $subject->Request()->getParam('elements');
+
```
Comment (felixbrucker) [inline Subscriber/Backend/ConfigSubscriber.php:37]:
```suggestion
```

File: Subscriber/Backend/ConfigSubscriber.php [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+        if ($data[0]['name'] !== 'stripeSecretKey') {
+            return;
+        }
+
+        $secretKey  = Util::stripeSecretKey();
+
```
Comment (felixbrucker) [inline Subscriber/Backend/ConfigSubscriber.php:43]:
```suggestion
```

File: Subscriber/Backend/ConfigSubscriber.php [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+    public function onAfterSaveFormAction(\Enlight_Hook_HookArgs $args)
+    {
+        $subject = $args->getSubject();
+        $data = $subject->Request()->getParam('elements');
+
+        if ($data[0]['name'] !== 'stripeSecretKey') {
+            return;
+        }
+
+        $secretKey  = Util::stripeSecretKey();
```
Comment (felixbrucker) [inline Subscriber/Backend/ConfigSubscriber.php:42]:
```suggestion
        $secretKey = Util::stripeSecretKey();
```

File: Util.php [hunk 8]
```diff
@@ -268,6 +270,16 @@ public static function getCustomerName()
         return trim($billingAddress->getFirstName() . ' ' . $billingAddress->getLastName());
     }
 
+    /**
+     * @return Stripe\Account The stripe account for the used secret key
+     */
+    public static function getAccount()
```
Comment (felixbrucker) [inline Util.php:276]:
```suggestion
    public static function getStripeAccount()
```

File: Bootstrap.php [hunk 9]
```diff
@@ -336,6 +338,15 @@ public function update($oldVersion)
...
+                    );
+
```
Comment (felixbrucker) [inline Bootstrap.php:345]:
```suggestion
```

**Review by felixbrucker — CHANGES_REQUESTED** [review]
Nice work!

File: Bootstrap.php [hunk 10]
```diff
@@ -336,6 +337,17 @@ public function update($oldVersion)
...
+                    $defaultShopLocale = $this->get('db')->fetchOne(
+                        'SELECT locale.locale
+                        FROM s_core_locales locale
+                        JOIN s_core_shops shop ON shop.locale_id = locale.id
+                        WHERE shop.default = 1'
+                    );
+                    $countryISO = explode('_', $defaultShopLocale)[1];
+
+                    Util::setConfigValue('stripeAccountCountryIso', 'string', $countryISO);
+                }
```
Comment (felixbrucker) [inline Bootstrap.php:350]: You'll want to add `'proxy',` to the list of `invalidateCache`s below at the end of this method, so that the subscriber works out of the box.

File: Subscriber/Backend/ConfigSubscriber.php [hunk 11]
```diff
@@ -0,0 +1,48 @@
...
+    /**
+     * Handle the retrieving of the stripe account country and saving it to a hidden config value
+     *
+     * @param \Enlight_Hook_HookArgs $args
+     */
+    public function onAfterSaveFormAction(\Enlight_Hook_HookArgs $args)
+    {
+        $subject = $args->getSubject();
+        $data = $subject->Request()->getParam('elements');
+        if ($data[0]['name'] !== 'stripeSecretKey') {
```
[the remark this answers is not in the document]
Comment (felixbrucker) [reply Subscriber/Backend/ConfigSubscriber.php:37]: This feels more robust than checking the first key of the elements to save

**Review by felixbrucker — CHANGES_REQUESTED** [review]
Almost there!

**Review by felixbrucker — APPROVED** [review]
LGTM

**Review by svenmuennich — APPROVED** [review]
