### PR TITLE
Clear one time credit cards from session after failed checkout

### LINKED ISSUE #91: Clear one-time-use payment information from Session after failed payment
# Current Behavior
When the payment fails and the customer is redirected back to the checkout of the shop, the payment information is still displayed even when the customer priorly chose not to save the payment information in his shop account.

# Why is this change necessary
As the customer opted that the payment information is not saved, Stripe cannot use the payment information again and hence the checkout fails when the customer does not re-enter the payment information before the retry of the checkout.

# How it should behave
When a customer chooses not to save the payment information and the payment fails, the payment information should be cleared from the session and not be displayed in the checkout after the redirect back to the shop. This applies to credit cards and probably also SEPA.

### PR DESCRIPTION
**Pull request by JanRogge**
Currently when a payment with a credit card fails we redirect to the checkout with the last selected card still selected.
This is a problem if the last card was a one time use card since it will not work anymore.

This PR changes this by removing one time credit cards from the session after a failed checkout.

Fixes #91

### CODE REVIEW

File: Util.php [hunk 1]
```diff
@@ -321,6 +321,21 @@ public static function resetStripeSession()
         Shopware()->Container()->get('session')->stripePayment = new \ArrayObject([], \ArrayObject::STD_PROP_LIST);
     }
 
+    /**
+     * Removes Cards that are not saved for future checkouts from the session.
+     */
+    public static function removeNotSavedCardFromSession()
```
Comment (felixbrucker) [inline Util.php:327]:
```suggestion
    public static function removeUnsavedSelectedCardFromSession()
```

File: Util.php [hunk 2]
```diff
@@ -321,6 +321,21 @@ public static function resetStripeSession()
...
+    {
+        $session = Shopware()->Container()->get('session')->stripePayment;
+
+        $saveCardForFutureCheckouts = array_key_exists('saveCardForFutureCheckouts', $session);
```
Comment (felixbrucker) [inline Util.php:331]:
```suggestion
        $hasSaveCardForFutureCheckouts = array_key_exists('saveCardForFutureCheckouts', $session);
```

File: Util.php [hunk 3]
```diff
@@ -321,6 +321,21 @@ public static function resetStripeSession()
...
+
+        if ($saveCardForFutureCheckouts && !$session->saveCardForFutureCheckouts) {
+            $session->selectedCard = [];
```
Comment (felixbrucker) [inline Util.php:334]: Why dont we `unset()` the selected card here?

File: CHANGELOG.md [hunk 4]
```diff
@@ -4,11 +4,13 @@
 
 * Fixes a bug that prevented payments with digital wallets (Apple Pay, Google Pay, ...) if the country of the customer and the country of the configured Stripe account differ.
     * For this purpose, the country of the Stripe account holder is automatically loaded from the account. For this, the plugin configuration must be saved again.
+* Fixes a bug that caused unsaved credit cards to continue to display when an order was completed incorrectly.
 
 ### de
 
 * Behebt einen Fehler, der dazu führte, dass Zahlungen mit Digital Wallets (Apple Pay, Google Pay, ...) nicht funktionierten, wenn sich das Land des Kunden und das des hinterlegten Stripe-Accounts unterscheiden.
     * Das Land des Stripe Accountinhabers wird hierfür automatisch aus dem Account geladen. Hierfür muss die Pluginkonfiguration neu gespeichert werden.
+* Behebt einen Fehler, der dazu führte, dass nicht gespeicherte Kreditkarten bei einem fehlerhaften Bestellabschluss weiterhin angezeigt wurden.
```
Comment (felixbrucker) [inline CHANGELOG.md:13]:
```suggestion
* Behebt einen Fehler, der dazu führte, dass nicht gespeicherte Kreditkarten nach einem fehlgeschlagenen Bestellabschluss weiterhin angezeigt wurden.
```

File: CHANGELOG.md [hunk 5]
```diff
@@ -4,11 +4,13 @@
 
 * Fixes a bug that prevented payments with digital wallets (Apple Pay, Google Pay, ...) if the country of the customer and the country of the configured Stripe account differ.
     * For this purpose, the country of the Stripe account holder is automatically loaded from the account. For this, the plugin configuration must be saved again.
+* Fixes a bug that caused unsaved credit cards to continue to display when an order was completed incorrectly.
```
Comment (felixbrucker) [inline CHANGELOG.md:7]:
```suggestion
* Fixes a bug that caused unsaved credit cards to continue to be displayed after a failed order completion.
```

**Review by felixbrucker — CHANGES_REQUESTED** [review]
Nice work!

**Review by felixbrucker — APPROVED** [review]
LGTM

**Review by svenmuennich — APPROVED** [review]
