### PR TITLE
Fix custom stripe snippet blocks for error messages

### LINKED ISSUE #102: javascript errors empty (regression in 5.4.0)
The transfer of error snippets (`frontend/plugins/payment/stripe_payment/digital_wallets` -- `error/*`) silently fails after a version 5.4.0 [change](https://github.com/pickware/ShopwareStripePayment/pull/88#discussion_r686357001) apparently motivated by a change in Shopware version 5.7.0

### PR DESCRIPTION
**Pull request by JanRogge**
Remove the escaped quotes at the start and end of the snippet name and namespace when parsing the snippet blocks to be consistent with shopware.

This fixes a problem were error messages were not shown because the snippet could not be loaded.

Closes #102

### CODE REVIEW

File: Classes/SmartyPlugins.php [hunk 1]
```diff
@@ -106,9 +106,9 @@ public function filterStripeSnippetBlocks($source, \Smarty_Internal_Template $te
 
             // Parse the snippet arguments to retrieve the snippet
             $hasNamespaceArg = preg_match('/(.?)(namespace=)(.*?)(?=(\\s|$))/', $blockArgs, $namespaceMatches);
-            $namespace = ($hasNamespaceArg && !empty($namespaceMatches[3])) ? trim($namespaceMatches[3]) : $defaultNamespace;
+            $namespace = ($hasNamespaceArg && !empty($namespaceMatches[3])) ? trim($namespaceMatches[3], '\\"') : $defaultNamespace;
             $hasNameArg = preg_match('/(.?)(name=)(.*?)(?=(\\s|$))/', $blockArgs, $nameMatches);
-            $name = ($hasNameArg && !empty($nameMatches[3])) ? trim($nameMatches[3]) : $blockContent;
+            $name = ($hasNameArg && !empty($nameMatches[3])) ? trim($nameMatches[3], '\\"') : $blockContent;
```
Comment (svenmuennich) [inline Classes/SmartyPlugins.php:111]: This no longer trims whitespace characters, does it?

Comment (JanRogge) [reply Classes/SmartyPlugins.php]: Oh you are right. I moved the triming of quotes to a seprate trim call now.

**Review by svenmuennich — APPROVED** [review]
